// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuffGolang/test1/packageOption.proto

package test1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PackageOption struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageOption) Reset()         { *m = PackageOption{} }
func (m *PackageOption) String() string { return proto.CompactTextString(m) }
func (*PackageOption) ProtoMessage()    {}
func (*PackageOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_66b3d2b23ace9295, []int{0}
}

func (m *PackageOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageOption.Unmarshal(m, b)
}
func (m *PackageOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageOption.Marshal(b, m, deterministic)
}
func (m *PackageOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageOption.Merge(m, src)
}
func (m *PackageOption) XXX_Size() int {
	return xxx_messageInfo_PackageOption.Size(m)
}
func (m *PackageOption) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageOption.DiscardUnknown(m)
}

var xxx_messageInfo_PackageOption proto.InternalMessageInfo

func (m *PackageOption) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PackageOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PackageOption) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*PackageOption)(nil), "test1.PackageOption")
}

func init() {
	proto.RegisterFile("protobuffGolang/test1/packageOption.proto", fileDescriptor_66b3d2b23ace9295)
}

var fileDescriptor_66b3d2b23ace9295 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x4b, 0x73, 0xcf, 0xcf, 0x49, 0xcc, 0x4b, 0xd7, 0x2f, 0x49, 0x2d, 0x2e,
	0x31, 0xd4, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0xf5, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0xd3,
	0x03, 0xab, 0x11, 0x62, 0x05, 0x4b, 0x29, 0xf9, 0x73, 0xf1, 0x06, 0x20, 0xcb, 0x0a, 0x09, 0x70,
	0x31, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x42, 0x5c,
	0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x04,
	0x17, 0x7b, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0x33, 0x58, 0x18, 0xc6, 0x75, 0xe2,
	0x88, 0x62, 0x4b, 0x2e, 0x2d, 0x2e, 0xc9, 0xcf, 0x4d, 0x62, 0x03, 0x5b, 0x64, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xf6, 0x15, 0x27, 0xaf, 0x95, 0x00, 0x00, 0x00,
}
