// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuffGolang/test1/simple.proto

package test1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleProto struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleProto) Reset()         { *m = SimpleProto{} }
func (m *SimpleProto) String() string { return proto.CompactTextString(m) }
func (*SimpleProto) ProtoMessage()    {}
func (*SimpleProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6c08bb8151c95d, []int{0}
}

func (m *SimpleProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleProto.Unmarshal(m, b)
}
func (m *SimpleProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleProto.Marshal(b, m, deterministic)
}
func (m *SimpleProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleProto.Merge(m, src)
}
func (m *SimpleProto) XXX_Size() int {
	return xxx_messageInfo_SimpleProto.Size(m)
}
func (m *SimpleProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleProto.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleProto proto.InternalMessageInfo

func (m *SimpleProto) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SimpleProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimpleProto) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*SimpleProto)(nil), "test1.SimpleProto")
}

func init() { proto.RegisterFile("protobuffGolang/test1/simple.proto", fileDescriptor_9e6c08bb8151c95d) }

var fileDescriptor_9e6c08bb8151c95d = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x4b, 0x73, 0xcf, 0xcf, 0x49, 0xcc, 0x4b, 0xd7, 0x2f, 0x49, 0x2d, 0x2e,
	0x31, 0xd4, 0x2f, 0xce, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x03, 0x4b, 0x0a, 0xb1, 0x82, 0xc5, 0x94,
	0x7c, 0xb9, 0xb8, 0x83, 0xc1, 0xc2, 0x01, 0x60, 0x51, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x53, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0x4f, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0x96, 0x60, 0x06, 0x0b, 0xc3, 0xb8, 0x49, 0x6c, 0x60, 0xc3, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x46, 0x2a, 0x37, 0xd2, 0x82, 0x00, 0x00, 0x00,
}
